project_name = "INPs_temperature"
seed = 1
load_it = "best"
batch_size = 64
num_epochs = 1000
sort_context = false
lr = 0.0001
decay_lr = 10
train_split = "train"
val_split = "val"
n_trials = 1
beta = 25.0
dataset = "temperature"
knowledge_type = "desc"
min_num_context = 0
max_num_context = 15
num_targets = 288
noise = 0.0
x_sampler = "random-uniform-15"
use_knowledge = true
text_encoder = "roberta"
freeze_llm = true
tune_llm_layer_norms = true
train_num_z_samples = 1
test_num_z_samples = 16
knowledge_dropout = 0.3
input_dim = 1
output_dim = 1
hidden_dim = 128
xy_encoder_num_hidden = 2
xy_encoder_hidden_dim = 384
xy_self_attention = "none"
xy_self_attention_num_layers = 1
data_agg_func = "cross-attention"
latent_encoder_num_hidden = 1
decoder_hidden_dim = 128
decoder_num_hidden = 3
decoder_activation = "gelu"
x_transf_dim = 128
x_encoder_num_hidden = 1
path = "latent"
knowledge_extractor_num_hidden = 2
knowledge_extractor_hidden_dim = 128
knowledge_merge = "sum"
knowledge_dim = 128
run_name_prefix = "inp_desc"
run_name_suffix = "tuned"
